# Generated by Django 4.1.7 on 2023-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.TextField()),
                ('password', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.TextField()),
                ('oa', models.TextField()),
                ('ultimo', models.DateTimeField(blank=True, null=True)),
                ('ip', models.TextField()),
                ('navegador', models.TextField()),
                ('accesos', models.IntegerField()),
            ],
            options={
                'db_table': 'administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.TextField()),
                ('password', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.TextField()),
                ('oa', models.TextField()),
                ('ultimo', models.DateTimeField(blank=True, null=True)),
                ('ip', models.TextField()),
                ('navegador', models.TextField()),
                ('accesos', models.IntegerField()),
            ],
            options={
                'db_table': 'alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnosAsignaturas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alumnos_asignaturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnosFamilias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_relacion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'alumnos_familias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_asignatura', models.TextField()),
            ],
            options={
                'db_table': 'asignaturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunicaciones',
            fields=[
                ('idcomunicacion', models.AutoField(primary_key=True, serialize=False)),
                ('tiporemite', models.IntegerField()),
                ('idremite', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('asunto', models.TextField()),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'comunicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComunicacionesAdjuntos',
            fields=[
                ('idcomunicacionadjunto', models.AutoField(primary_key=True, serialize=False)),
                ('adjunto', models.TextField()),
            ],
            options={
                'db_table': 'comunicaciones_adjuntos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComunicacionesDestinos',
            fields=[
                ('idcomunicaciondestino', models.AutoField(primary_key=True, serialize=False)),
                ('tipodestino', models.IntegerField()),
                ('iddestino', models.IntegerField()),
                ('leida', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.DateTimeField(blank=True, null=True)),
                ('email', models.IntegerField()),
                ('importante', models.IntegerField()),
            ],
            options={
                'db_table': 'comunicaciones_destinos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursosEscolares',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('curso_escolar', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cursos_escolares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('id_grupo', models.IntegerField()),
                ('documento', models.TextField()),
                ('enlace', models.TextField()),
                ('categoria', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentosAlumno',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.TextField()),
                ('enlace', models.TextField()),
                ('categoria', models.TextField()),
                ('fecha', models.DateField()),
                ('token', models.TextField()),
                ('curso_documento', models.TextField()),
                ('curso_alumno', models.TextField()),
                ('ip', models.TextField(blank=True, null=True)),
                ('descarga_id', models.IntegerField()),
                ('descarga_fecha', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'documentos_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.TextField()),
                ('password', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.TextField()),
                ('oa', models.TextField()),
                ('ultimo', models.DateTimeField(blank=True, null=True)),
                ('ip', models.TextField()),
                ('navegador', models.TextField()),
                ('accesos', models.IntegerField()),
                ('fcm_token', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'familias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliasAppAjustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autentificacion_dos_fases', models.IntegerField()),
                ('proteccion_restablecimiento', models.IntegerField()),
                ('not_comunicaciones_push', models.IntegerField()),
                ('not_calificaciones_push', models.IntegerField()),
                ('not_entrevistas_push', models.IntegerField()),
                ('not_extraescolares_push', models.IntegerField()),
                ('not_enfermeria_push', models.IntegerField()),
                ('not_comunicaciones_email', models.IntegerField()),
                ('not_calificaciones_email', models.IntegerField()),
                ('not_entrevistas_email', models.IntegerField()),
                ('not_extraescolares_email', models.IntegerField()),
                ('not_enfermeria_email', models.IntegerField()),
            ],
            options={
                'db_table': 'familias_app_ajustes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('diasemana', models.IntegerField()),
                ('modulo', models.IntegerField()),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llavero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aplicacion', models.TextField()),
                ('usuario', models.TextField()),
                ('email', models.TextField()),
                ('contraseña', models.TextField()),
                ('modificable', models.IntegerField()),
            ],
            options={
                'db_table': 'llavero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcoHorario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.IntegerField()),
                ('diasemana', models.IntegerField()),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
            options={
                'db_table': 'marco_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=250)),
                ('tutor', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'materias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorAsignaturas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profesor_asignaturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.TextField()),
                ('password', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('nacimiento', models.DateField()),
                ('dni', models.TextField()),
                ('oa', models.TextField()),
                ('ultimo', models.DateTimeField(blank=True, null=True)),
                ('ip', models.TextField()),
                ('navegador', models.TextField()),
                ('accesos', models.IntegerField()),
            ],
            options={
                'db_table': 'profesores',
                'managed': False,
            },
        ),
    ]
